version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: football-db
    restart: always
    environment:
      POSTGRES_DB: football_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
