spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football_db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/football_db
    user: postgres
    password: secret
    baseline-on-migrate: true
    locations: classpath:db.migration
    validate-on-migrate: true

jwt:
  secret: your-very-secure-random-key-32bytes
  expiration: 3600000

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    org.flywaydb: DEBUG
