CREATE TABLE public.app_user (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    password     VARCHAR(255),
    email        VARCHAR(255)
);

CREATE TABLE public.team (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competitor_id VARCHAR(255) UNIQUE NOT NULL,
    name         VARCHAR(255),
    short_name   VARCHAR(255),
    abbreviation VARCHAR(10)
);

CREATE TABLE public.user_favorite_team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    UNIQUE (user_id, team_id),
    FOREIGN KEY (user_id) REFERENCES public.app_user (id) ON DELETE CASCADE,
    FOREIGN KEY (team_id) REFERENCES public.team (id) ON DELETE CASCADE
);
